config/routes.rb
Rails.application.routes.draw do
  root 'static#home'
  get 'static/dashboard'
  resources :quotations
  resources :tubes
  resources :ratios
  resources :losses
  resources :individuals
  resources :companies
  resources :matters do
    collection do
      post :import
    end
  end
  resources :categories
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/ratio.rb
class Ratio < ApplicationRecord
end

app/controllers/ratios_controller.rb
class RatiosController < ApplicationController
  before_action :set_ratio, only: %i[ show edit update destroy ]

  # GET /ratios or /ratios.json
  def index
    @ratios = Ratio.all
  end

  # GET /ratios/1 or /ratios/1.json
  def show
  end

  # GET /ratios/new
  def new
    @ratio = Ratio.new
  end

  # GET /ratios/1/edit
  def edit
  end

  # POST /ratios or /ratios.json
  def create
    @ratio = Ratio.new(ratio_params)

    respond_to do |format|
      if @ratio.save
        format.html { redirect_to ratio_url(@ratio), notice: "Ratio was successfully created." }
        format.json { render :show, status: :created, location: @ratio }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ratio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ratios/1 or /ratios/1.json
  def update
    respond_to do |format|
      if @ratio.update(ratio_params)
        format.html { redirect_to ratio_url(@ratio), notice: "Ratio was successfully updated." }
        format.json { render :show, status: :ok, location: @ratio }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ratio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ratios/1 or /ratios/1.json
  def destroy
    @ratio.destroy

    respond_to do |format|
      format.html { redirect_to ratios_url, notice: "Ratio was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ratio
      @ratio = Ratio.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ratio_params
      params.require(:ratio).permit(:dn, :tps_demandrinage, :ratio_ac, :ratio_rm)
    end
end

app/helpers/ratios_helper.rb
module RatiosHelper
end

app/views/ratios/_form.html.erb
<%= form_with(model: ratio) do |form| %>
  <% if ratio.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(ratio.errors.count, "error") %> prohibited this ratio from being saved:</h2>

      <ul>
        <% ratio.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :dn, style: "display: block" %>
    <%= form.number_field :dn %>
  </div>

  <div>
    <%= form.label :tps_demandrinage, style: "display: block" %>
    <%= form.text_field :tps_demandrinage %>
  </div>

  <div>
    <%= form.label :ratio_ac, style: "display: block" %>
    <%= form.text_field :ratio_ac %>
  </div>

  <div>
    <%= form.label :ratio_rm, style: "display: block" %>
    <%= form.text_field :ratio_rm %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/ratios/_ratio.html.erb
<div id="<%= dom_id ratio %>">
  <p>
    <strong>Dn:</strong>
    <%= ratio.dn %>
  </p>

  <p>
    <strong>Tps demandrinage:</strong>
    <%= ratio.tps_demandrinage %>
  </p>

  <p>
    <strong>Ratio ac:</strong>
    <%= ratio.ratio_ac %>
  </p>

  <p>
    <strong>Ratio rm:</strong>
    <%= ratio.ratio_rm %>
  </p>

</div>

app/views/ratios/edit.html.erb
<h1>Editing ratio</h1>

<%= render "form", ratio: @ratio %>

<br>

<div>
  <%= link_to "Show this ratio", @ratio %> |
  <%= link_to "Back to ratios", ratios_path %>
</div>

app/views/ratios/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Ratios</h1>

<div id="ratios">
  <% @ratios.each do |ratio| %>
    <%= render ratio %>
    <p>
      <%= link_to "Show this ratio", ratio %>
    </p>
  <% end %>
</div>

<%= link_to "New ratio", new_ratio_path %>

app/views/ratios/new.html.erb
<h1>New ratio</h1>

<%= render "form", ratio: @ratio %>

<br>

<div>
  <%= link_to "Back to ratios", ratios_path %>
</div>

app/views/ratios/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @ratio %>

<div>
  <%= link_to "Edit this ratio", edit_ratio_path(@ratio) %> |
  <%= link_to "Back to ratios", ratios_path %>

  <%= button_to "Destroy this ratio", @ratio, method: :delete %>
</div>