config/routes.rb
Rails.application.routes.draw do
  root 'static#home'
  get 'static/dashboard'
  resources :quotations
  resources :tubes
  resources :ratios
  resources :losses
  resources :individuals
  resources :companies
  resources :matters do
    collection do
      post :import
    end
  end
  resources :categories
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/quotation.rb
class Quotation < ApplicationRecord
  belongs_to :company
  has_many :tubes
end

app/controllers/quotations_controller.rb
class QuotationsController < ApplicationController
  before_action :set_quotation, only: %i[ show edit update destroy ]

  # GET /quotations or /quotations.json
  def index
    @quotations = Quotation.all
  end

  # GET /quotations/1 or /quotations/1.json
  def show
  end

  # GET /quotations/new
  def new
    @quotation = Quotation.new
  end

  # GET /quotations/1/edit
  def edit
  end

  # POST /quotations or /quotations.json
  def create
    @quotation = Quotation.new(quotation_params)

    respond_to do |format|
      if @quotation.save
        format.html { redirect_to quotation_url(@quotation), notice: "Quotation was successfully created." }
        format.json { render :show, status: :created, location: @quotation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @quotation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotations/1 or /quotations/1.json
  def update
    respond_to do |format|
      if @quotation.update(quotation_params)
        format.html { redirect_to quotation_url(@quotation), notice: "Quotation was successfully updated." }
        format.json { render :show, status: :ok, location: @quotation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @quotation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotations/1 or /quotations/1.json
  def destroy
    @quotation.destroy

    respond_to do |format|
      format.html { redirect_to quotations_url, notice: "Quotation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quotation
      @quotation = Quotation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def quotation_params
      params.require(:quotation).permit(:company_id)
    end
end

app/helpers/quotations_helper.rb
module QuotationsHelper
end

app/views/quotations/_form.html.erb
<%= form_with(model: quotation) do |form| %>
  <% if quotation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(quotation.errors.count, "error") %> prohibited this quotation from being saved:</h2>

      <ul>
        <% quotation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :company_id, style: "display: block" %>
    <%= form.text_field :company_id %>
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/quotations/_quotation.html.erb
<div id="<%= dom_id quotation %>">
  <p>
    <strong>Company:</strong>
    <%= quotation.company_id %>
  </p>

</div>

app/views/quotations/edit.html.erb
<h1>Editing quotation</h1>

<%= render "form", quotation: @quotation %>

<br>

<div>
  <%= link_to "Show this quotation", @quotation %> |
  <%= link_to "Back to quotations", quotations_path %>
</div>

app/views/quotations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Quotations</h1>

<div id="quotations">
  <% @quotations.each do |quotation| %>
    <%= render quotation %>
    <p>
      <%= link_to "Show this quotation", quotation %>
    </p>
  <% end %>
</div>

<%= link_to "New quotation", new_quotation_path %>

app/views/quotations/new.html.erb
<h1>New quotation</h1>

<%= render "form", quotation: @quotation %>

<br>

<div>
  <%= link_to "Back to quotations", quotations_path %>
</div>

app/views/quotations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @quotation %>

<div>
  <%= link_to "Edit this quotation", edit_quotation_path(@quotation) %> |
  <%= link_to "Back to quotations", quotations_path %>

  <%= button_to "Destroy this quotation", @quotation, method: :delete %>
</div>