config/routes.rb
Rails.application.routes.draw do
  root 'static#home'
  get 'static/dashboard'
  resources :quotations
  resources :tubes
  resources :ratios
  resources :losses
  resources :individuals
  resources :companies
  resources :matters do
    collection do
      post :import
    end
  end
  resources :categories
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/tube.rb
class Tube < ApplicationRecord
    belongs_to :quotation
   
    COEFF_TEPHANE = 0.013
    EPVOILE_AC = 0.3
    EPMAT = 0.7
    POIDS_VOILE_M2 = 0.02
    POIDS_MAT = 0.3
    TAUX_ABS_VOILE = 15
    TAUX_ABS_MAT = 2.5
    POURCENTAGE_MAJ_MATIERE = 0.05
    POURCENTAGE_MAJ_VOILE = 0.15
    EP_FIL_PROJ = 0.55
    POIDS_FIL_PROJ_M2 = 0.3
    TAUX_ABS_FIBRE_PROJ = 2.5
    POIDS_UD = 0.04
    POIDS_UD_M2 = 0.3
    LARGEUR_NAPPE = 0.23
    POURCENTAGE_MAJ_FIL_DIRECT = 0.01
    POIDS_FILS_TEX = 2.4
    EPAISSEUR_NAPPE_MVP = 0.7
    EPAISSEUR_NAPPE_PLASTREX = 1.1
    EPAISSEUR_VOILE_FINITION = 0.2
    RATIO_COLORANT = "3%"
    CHARGE_ANTI_ABRASION = "1%"
    AUTRE_CHARGE_AC = "1%"
    ANTI_UV_326 = "0.2451%"
    AUTRE_CHARGE = "0.20%"
    RATIO_LPT = 0.02
    RATIO_COBALT = 0.003
    RATIO_DMA = 0.001

   
  
    def f_1
       qt = self.quantity.to_f
       dn = self.dn
       aray_dn_values = find_dn_values(dn)
       useful_quantity = aray_dn_values[0].to_f
       nmbr_tube = (qt / useful_quantity).ceil
       return nmbr_tube
    end


    def f_2
      dn = self.dn
      qt = self.quantity.to_f
      type_piece = self.type_piece
      rm = self.rm 
      
      if type_piece == "TUBE ORTHO"
        aray_dn_values = find_dn_values(dn)
        coef_loss = aray_dn_values[1]
      else
        aray_dn_values = find_dn_values(dn)
        coef_loss = aray_dn_values[2]
      end
      rm_loss = coeff_pert(type_piece,rm)

      return   coef_loss * rm_loss

    end


    def f_3
       dn = self.dn
       qt = self.quantity.to_f
       reel_loss = self.f_2()
       nmbr_tube = self.f_1()
       type_piece = self.type_piece
       rm = self.rm
       array_dn_values = find_dn_values(dn)
       lenght_useful = array_dn_values[0]

       if dn <600 && dn !=450
          qt_calculation = qt*(lenght_useful+reel_loss)
       else
        qt_calculation= nmbr_tube*reel_loss + qt
       end

    end


    def f_4
       dn = self.dn
       qt_calculation = self.f_3()
       surface = (Math::PI * dn / 1000 *qt_calculation).round(2)
    end


    def f_5
        dn = self.dn
        surface = self.f_4
        coeff_demoulant_f57_ncp = 0.0085
        coeff_terphane = 0.013
        percentage_maj_matter = 0.2
    
        if dn < 600
           demoulant= (surface * coeff_demoulant_f57_ncp).round(2)
           matter_demoulant = "DEMOULANT F57 NCP"
        else
            demoulant = (surface * coeff_terphane * (1+percentage_maj_matter)).round(2)
            matter_demoulant = "Terphane lg 50 MM-EP 36µ"
        end
       return demoulant, matter_demoulant
    end


    def f6_7
      if self.dn && self.dn < 600
        f6
      else
        f7
      end

    end

    def f8_9
     if self.type_piece == "TUBE ORTHO"
      f8()
     else
      f9()
     end
    end

    def f_10 #VERIFY 
      dn = self.dn
      qt_calcul=self.f_3
      ac = self.ac
      rm = self.rm
      surface_voile_fin = qt_calcul * (dn + 2 * ac + 2* rm ) * Math::PI * (1 + POURCENTAGE_MAJ_VOILE)/1000
      poids_resine_voile = surface_voile_fin * POIDS_VOILE_M2 * TAUX_ABS_VOILE * (1+ POURCENTAGE_MAJ_MATIERE)
      if self.type_piece =="TUBE ORTHO" 
        poids = f8()
        poids_rm = poids[3]
      else
        poids= f9()
        poids_rm = poids[3]
      end
      poids_total = poids_resine_voile + poids_rm

      return surface_voile_fin.round, poids_resine_voile.round, poids_total.round
    end

    def f_11
        charge_ac = self.charge_ac
        charge_rm = self.charge_rm
        couleur = self.color
        if color != "AUCUN"
          ratio_pate_couleur = 0.03
        end
        if charge_ac =="CHARGE ANTI ABRASION" || charge_ac == "autre charge"
          ratio_charge_ac = 0.01
        else
          ratio_charge_ac = 0
        end
        if charge_rm == "ANTI UV 326" || charge_rm == "autre charge"
          ratio_charge_rm = 0.002
        else
          ratio_charge_rm = 0
        end
        poids = f6_7()
        poids_resine_acvr = poids[1]
        poids_rm = f8_9()
        poids_resine_rm = poids_rm[2]

        poids_charge_ac = poids_resine_acvr * ratio_charge_ac
        poids_charge_rm = poids_resine_rm * ratio_charge_rm
        poids_charge_color = poids_resine_rm * ratio_pate_couleur

        return poids_charge_ac.round(3), poids_charge_rm, poids_charge_color
    end
 
    def f_12
       poids_total_ac = f6_7()[3]
       poids_total_rm = f8_9()[3]
       dn = self.dn 
       nmbr_tube = f_1()
       tps_demand = find_ratios_by_dn(dn)[0]
   
       ratio_ac = find_ratios_by_dn(dn)[1]
       ratio_rm = find_ratios_by_dn(dn)[2]
       mo = ratio_ac * poids_total_ac + ratio_rm * poids_total_rm + nmbr_tube * tps_demand
     return mo.round
    end
 
    def f_13
        poids_resine_ac = f6_7()[1] 
        poids_resin_rm = f8_9()[2]

        poids_butanox = (poids_resine_ac + poids_resin_rm) * RATIO_LPT
        poids_cobalt = (poids_resine_ac + poids_resin_rm) * RATIO_COBALT
        poids_dma = (poids_resine_ac + poids_resin_rm) * RATIO_DMA
        return poids_butanox.round(2), poids_cobalt.round(3), poids_dma.round(3)
    end
    #### PRICE INTERMEDIATE CALCULATION ##########
    def calculation 
      designiation = self.barear_ac
      matter_ac ||= Matter.find_by(name: designiation)# || { id: 4, name: "RESINE EQUIVALENTE 470", price_local: 7.29, price_export: 6.69, category_id: 1 }   
      price_ac = self.country == 'export' ? matter_ac[:price_export] :  matter_ac[:price_local]
      quantity_ac = f6_7()[1] 
      price_ac_total = quantity_ac.round() * price_ac

      designation_rm = self.resine_rm
      matter_rm ||= Matter.find_by(name: designation_rm)# || { id: 4, name: "RESINE EQUIVALENTE 411", price_local: 4.87, price_export: 4.47, category_id: 1 }
      price_rm =  self.country == 'export' ? matter_rm[:price_export] :  matter_rm[:price_local]
      quantity_rm = f_10()[1]+f8_9()[2]
      price_rm_total = quantity_rm.round() * price_rm

      surface_voile = f_10()[0]
      matter_surface = Matter.find_by(name: '1702 lg 50 MM')# || { id: 4, name: "1702 lg 50 MM", price_local: 1.27, price_export: 1.10, category_id: 1 }
      price_matter_surface =  self.country == 'export' ? matter_surface[:price_export] :  matter_surface[:price_local]
      price_matter_surface_total = surface_voile * price_matter_surface
    
      designation_voile_ac = self.voile_ac
      surface_voile_ac = f6_7()[0]
      matter_voile_ac = Matter.find_by(name: designation_voile_ac) #|| { id: 4, name: "1777 lg 50 MM", price_local: 0.95, price_export: 0.83, category_id: 1 }
      price_matter_voile_ac = self.country == 'export' ? matter_voile_ac[:price_export] :  matter_voile_ac[:price_local]
      price_matter_voile_ac_total = surface_voile_ac * price_matter_voile_ac

      if f_5()[1]==  "Terphane lg 50 MM-EP 36µ"
        terphane = Matter.find_by(name:  "Terphane lg 50 MM-EP 36µ")
        terphane_price = self.country == 'export' ? 5 : 5.75
        terphane_weight = f_5()[0]
        price_terphane_total = terphane_price * terphane_weight
      else
        price_terphane_total = 0
      end
      if self.dn < 600
        matter_poudre = Matter.find_by(name:  "MAT  POUDRE 300 lg 100" )
        matter_poudre_price = self.country == 'export' ? 3.31 : 3.80
        matter_poudre_weight = f6_7()[2]
        matter_poudre_price_total = matter_poudre_price * matter_poudre_weight  
      else
        matter_poudre_price_total= 0
      end

      if self.type_piece == "TUBE ORTHO"
        qt_tissu_unidrect = f8_9()[0]
        matter_tissu_undirect = Matter.find_by(name:  "TISSU UNIDIRECTIONNEL" )
        price_matter_tissu_undirect = self.country == 'export' ? 2.45 :2.82
        price_matter_tissu_undirect_total = price_matter_tissu_undirect * qt_tissu_unidrect

        qt_fil = f8_9()[1]
        matter_fil = Matter.find_by(name:   "FIL 2400 TEX ENROULEMENT")
        price_matter_fil =  self.country == 'export' ? 1.50 : 1.73
        price_matter_fil_total = qt_fil *  price_matter_fil

        if  self.dn >= 600
          qt_fil_projection = f6_7()[2]
          matter_fill_projection = Matter.find_by(name:   "FIL 2400 TEX PROJECTION")
          price_matter_fil_projection =  self.country == 'export' ? 1.95 : 2.25
          price_matter_fil_projection_total=  price_matter_fil_projection * qt_fil_projection

        else
          price_matter_fil_projection_total = 0
        end

      else
        price_matter_tissu_undirect_total= 0
        price_matter_fil_total = 0
        price_matter_fil_projection_total= 0
      end
      
       poids_dma= f_13()[2]
       matter_dma = Matter.find_by(name:    "ACCELERATEUR DMA 100%")
       price_matter_dma = self.country == 'export' ? 9.03 : 9.03
       price_matter_dma_total = poids_dma *  price_matter_dma

        
       poids_cobalt= f_13()[1]
       matter_cobalt = Matter.find_by(name:    "ACCELERATEUR COBALT 6%")
       price_matter_cobalt = self.country == 'export' ? 9.94 : 9.94
       price_matter_cobalt_total = poids_cobalt *  price_matter_cobalt

       poids_catalyseur_lpt = f_13()[0]
       matter_catalyseur_lpt =  Matter.find_by(name:    "CATALYSEUR LPT")
       price_catalyseur_lpt = self.country == 'export' ?  5.93 : 5.93
       price_catalyseur_lpt_total= price_catalyseur_lpt * poids_catalyseur_lpt
      
       
      if self.charge_rm == "ANTI UV 326"
        qt_anti_uv = f_11()[1]
        matter_anti_uv = Matter.find_by(name:    "ANTI UV 326")
        price_matter_anti_uv =  self.country == 'export' ?  30.25 : 30.25
        price_matter_anti_uv_total =  price_matter_anti_uv *  qt_anti_uv

      else
        price_matter_anti_uv_total= 0 
      end
      if f_5()[1]==  "DEMOULANT F57 NCP"
      qt_demoulant = f_5()[0]
      matter_demoulant = Matter.find_by(name:   "DEMOULANT F57 NCP"  )
      price_matter_demoulant =  self.country == 'export' ?  12.52 : 12.52
      price_matter_demoulant_total=  price_matter_demoulant * qt_demoulant
      else
        price_matter_demoulant_total= 0
      end
      

app/controllers/tubes_controller.rb
class TubesController < ApplicationController
  before_action :set_tube, only: %i[ show edit update destroy ]

  # GET /tubes or /tubes.json
  def index
    @tubes = Tube.all
  end

  # GET /tubes/1 or /tubes/1.json
  def show
  end

  # GET /tubes/new
  def new
    @tube = Tube.new
  end

  # GET /tubes/1/edit
  def edit
  end

  # POST /tubes or /tubes.json
  def create
    @tube = Tube.new(tube_params)

    respond_to do |format|
      if @tube.save
        format.html { redirect_to tube_url(@tube), notice: "Tube was successfully created." }
        format.json { render :show, status: :created, location: @tube }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tube.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tubes/1 or /tubes/1.json
  def update
    respond_to do |format|
      if @tube.update(tube_params)
        format.html { redirect_to tube_url(@tube), notice: "Tube was successfully updated." }
        format.json { render :show, status: :ok, location: @tube }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tube.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tubes/1 or /tubes/1.json
  def destroy
    @tube.destroy

    respond_to do |format|
      format.html { redirect_to tubes_url, notice: "Tube was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tube
      @tube = Tube.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tube_params
      params.require(:tube).permit(:country, :pressure, :mat, :type_piece, :dn, :ac, :rm, :quantity, :price_mo, :voile_ac, :barear_ac, :charge_ac, :resine_rm, :charge_rm, :color, :number_voile_ac, :quotation_id)
    end
end

app/helpers/tubes_helper.rb
module TubesHelper
end

app/views/tubes/_form.html.erb
<%= form_with(model: tube) do |form| %>
  <% if tube.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tube.errors.count, "error") %> prohibited this tube from being saved:</h2>

      <ul>
        <% tube.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :country, style: "display: block" %>
   <%= form.select :country, ['export', 'local'] %>
  </div>

  <div>
    <%= form.label :pressure, style: "display: block" %>
    <%= form.number_field :pressure %>
  </div>

  <div>
    <%= form.label :mat, style: "display: block" %>
    <%= form.text_field :mat, value: "SVR" %>
  </div>

  <div>
    <%= form.label :type_piece, style: "display: block" %>
    <%= form.select :type_piece, ['TUBE ORTHO', 'TUBE HELI'] %>
  </div>

  <div>
    <%= form.label :dn, style: "display: block" %>
    <%= form.number_field :dn %>
  </div>

  <div>
    <%= form.label :ac, style: "display: block" %>
    <%= form.text_field :ac %>
  </div>

  <div>
    <%= form.label :rm, style: "display: block" %>
    <%= form.text_field :rm %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.label :price_mo, style: "display: block" %>
    <%= form.number_field :price_mo %>
  </div>

  <div>
    <%= form.label :voile_ac, style: "display: block" %>
    <%= form.select :voile_ac,["1777 lg 50 MM","1773 lg 50 MM"] %>
  </div>

  <div>
    <%= form.label :barear_ac, style: "display: block" %>
    <%= form.select :barear_ac,[ "RESINE EQUIVALENTE 470", "RESINE EQUIVALENTE 411", "RESINE PISCINE", "RESINE DK MOMENTUM 411-350", "RESINE ISOPHTALIQUE", "RESINE ACCROCHAGE PVC", "RESINE DK 470-300" ] %>
  </div>

  <div>
    <%= form.label :charge_ac, style: "display: block" %>
    <%= form.select :charge_ac , ["AUCUN","CHARGE ANTI ABRASION","autre charge"]%>
  </div>

  <div>
    <%= form.label :resine_rm, style: "display: block" %>
    <%= form.select :resine_rm,[ "RESINE EQUIVALENTE 470", "RESINE EQUIVALENTE 411", "RESINE PISCINE", "RESINE DK MOMENTUM 411-350", "RESINE ISOPHTALIQUE", "RESINE ACCROCHAGE PVC", "RESINE DK 470-300" ] %>
  </div>

  <div>
    <%= form.label :charge_rm, style: "display: block" %>
    <%= form.select :charge_rm, ["AUCUN", "ANTI UV 326", "AEROSIL"] %>
  </div>

  <div>
    <%= form.label :color, style: "display: block" %>
    <%= form.select :color, ["AUCUN", "PATE COLORANTE", "AUTRE COULEUR"] %>
  </div>

  <div>
    <%= form.label :number_voile_ac, style: "display: block" %>
    <%= form.number_field :number_voile_ac %>
  </div>
    <div>
    <%= form.label :quotation_id, style: "display: block" %>
    <%= form.number_field :quotation_id %>
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tubes/_tube.html.erb
<div id="<%= dom_id tube %>">
  <p>
    <strong>Country:</strong>
    <%= tube.country %>
  </p>

  <p>
    <strong>Pressure:</strong>
    <%= tube.pressure %>
  </p>

  <p>
    <strong>Mat:</strong>
    <%= tube.mat %>
  </p>

  <p>
    <strong>Type piece:</strong>
    <%= tube.type_piece %>
  </p>

  <p>
    <strong>Dn:</strong>
    <%= tube.dn %>
  </p>

  <p>
    <strong>Ac:</strong>
    <%= tube.ac %>
  </p>

  <p>
    <strong>Rm:</strong>
    <%= tube.rm %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= tube.quantity %>
  </p>

  <p>
    <strong>Price mo:</strong>
    <%= tube.price_mo %>
  </p>

  <p>
    <strong>Voile ac:</strong>
    <%= tube.voile_ac %>
  </p>

  <p>
    <strong>Barear ac:</strong>
    <%= tube.barear_ac %>
  </p>

  <p>
    <strong>Charge ac:</strong>
    <%= tube.charge_ac %>
  </p>

  <p>
    <strong>Resine rm:</strong>
    <%= tube.resine_rm %>
  </p>

  <p>
    <strong>Charge rm:</strong>
    <%= tube.charge_rm %>
  </p>

  <p>
    <strong>Color:</strong>
    <%= tube.color %>
  </p>
   <p>
    <strong>Voile AC</strong>
    <%= tube.number_voile_ac %>
  </p>


  <p>
    <strong>Prix par pièce </strong>
    <%= tube.price_mp.ceil %> euro
  </p>
  <p>
    <strong>Prix par Final </strong>
    <%= tube.price_mgcom.ceil() %> euro
  </p>
</div>
<table>
  <thead>
    <tr>
      <th>Column 1</th>
      <th>Column 2</th>
      <th>Column 3</th>
      <th>Column 4</th>
      <th>Column 5</th>
      <th>Column 6</th>
      <th>Column 7</th>
      <th>Column 8</th>
      <th>Column 9</th>
      <th>Column 10</th>
      <th>Column 11</th>
  
    </tr>
  </thead>
    <tbody>

      <tr>
        <td><%= tube.f_1 %></td>
        <td><%= tube.f_2  %></td>
        <td><%= tube.f_3  %></td>
        <td><%= tube.f_4 %></td>
        <td><%= tube.f_5 %></td>
        <td><%= tube.f6_7 %></td>
        <td><%= tube.f8_9 %></td>
        <td><%= tube.f_10 %></td>
        <td><%= tube.f_11 %></td>
        <td><%= tube.f_12 %></td>
        <td><%= tube.f_13%></td>
   
      </tr>

  </tbody>
</table>

app/views/tubes/edit.html.erb
<h1>Editing tube</h1>

<%= render "form", tube: @tube %>

<br>

<div>
  <%= link_to "Show this tube", @tube %> |
  <%= link_to "Back to tubes", tubes_path %>
</div>

app/views/tubes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tubes</h1>

<div id="tubes">
  <% @tubes.each do |tube| %>
    <%= render tube %>
    <p>
      <%= link_to "Show this tube", tube %>
    </p>
  <% end %>
</div>

<%= link_to "New tube", new_tube_path %>

app/views/tubes/new.html.erb
<h1>New tube</h1>

<%= render "form", tube: @tube %>

<br>

<div>
  <%= link_to "Back to tubes", tubes_path %>
</div>

app/views/tubes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tube %>

<div>
  <%= link_to "Edit this tube", edit_tube_path(@tube) %> |
  <%= link_to "Back to tubes", tubes_path %>

  <%= button_to "Destroy this tube", @tube, method: :delete %>
</div>